### ISSUE TITLE
issue with ts-reference-ci-scripts

### ISSUE THREAD

**Issue by superyyrrzz** [docascode/type2docfx#3]
Original comment: https://github.com/dotnet/docfx/issues/2220#issuecomment-374148129
> Is there some additional documentation for the ts-reference-ci-scripts tool? It seems like it is checked in on a private vsts. I always get the message No source file for mypackage.

**Comment by superyyrrzz** [comment]
@crazyfx1 Move here to avoid a super long issue.

What kind of question do you have? `ts-reference-ci-scripts` core component is this `type2docfx`, which is open sourced.

I can not reproduce your fail install. Could you provide more information like npm version, full error log?

**Comment by crazyfx1** [comment]
Thanks. 
I did some digging and fount out that the source code has to be in a lib-Folder. Since my component is not a npm component strictly speaking, the code is in another folder. Is there a way to configure the source folder?

When I moved the code into the lib folder for testing, I've seen that you need to have installed type2docfx globally on your pc. You might want to add this to the documentation.

**Comment by superyyrrzz** [comment]
Maybe you should use type2docfx instead of ts-reference-ci-scripts in this case. @wuhanyumsft Am I right? Is it supported now?

**Comment by ovasquez** [comment]
@superyyrrzz since this issue is already open, I noticed that `ts-reference-ci-scripts` overwrites everything in the yml directory that it's supposed to be created which sometimes is not desired (because it deletes the index.md and the .gitignore files that were created by docfx)

Is there any chance for this package to get open sourced so the community can start helping with it?

**Comment by superyyrrzz** [comment]
@ovasquez `ts-reference-ci-scripts` is initially used for CI purpose. I agree this behavior is not desirable in other scenario. Instead, `type2docfx` is more general, and also open source. We will update the document to use this tool.

**Comment by superyyrrzz** [comment]
document updated: http://dotnet.github.io/docfx/tutorial/universalreference/gen_doc_for_ts.html

Close this issue as `ts-reference-ci-scripts` should not be used. The issue mentioned here doesn't exist in `type2docfx`
